// Static job-template catalog (product config, not user data — see api.ts note).
import type { JobTemplate } from './types';

export const JOB_TEMPLATES: JobTemplate[] = [
  {
    id: 'bug_fix', name: 'Bug fix', shortLabel: 'Fix a bug', icon: 'alert',
    description: 'Reproduces the issue, fixes it and opens a PR with a regression test.',
    inputLabel: 'Repo + issue URL', outputLabel: 'PR fixing the issue',
    placeholder: 'Paste an issue URL or describe the bug to fix',
    tools: ['fs', 'shell', 'git', 'GitHub API', 'tests'],
    approvals: ['Force push', 'Installing system packages'],
    criteria: ['Failing test reproduces the bug', 'Test passes after the fix', 'Diff touches only related files'],
    checks: ['Tests', 'Lint and typecheck', 'No secrets added'],
  },
  {
    id: 'feature_impl', name: 'Feature implementation', shortLabel: 'Build a feature', icon: 'spark',
    description: 'Plans the work, writes the code and tests, and opens a PR.',
    inputLabel: 'Repo + spec', outputLabel: 'PR with feature and tests',
    placeholder: 'Describe the feature you want built',
    tools: ['fs', 'shell', 'git', 'browser', 'db', 'tests'],
    approvals: ['Database migrations', 'Using a secret', 'Spending money'],
    criteria: ['Feature works end to end in preview', 'New tests cover the happy path and one failure', 'PR description matches the diff'],
    checks: ['Tests', 'Build', 'Lint and typecheck', 'Minimal diff'],
  },
  {
    id: 'refactor', name: 'Refactor', shortLabel: 'Refactor', icon: 'retry',
    description: 'Restructures code without changing behavior and proves it with the existing tests.',
    inputLabel: 'Repo + target', outputLabel: 'PR with refactor',
    placeholder: 'What should be refactored, and what must not change?',
    tools: ['fs', 'shell', 'git', 'tests'],
    approvals: ['Deleting files (rm -rf)'],
    criteria: ['All existing tests pass unchanged', 'No public API changes'],
    checks: ['Tests', 'Typecheck', 'Diff is coherent'],
  },
  {
    id: 'db_migration', name: 'Database migration', shortLabel: 'Migrate a database', icon: 'db',
    description: 'Generates schema-aware SQL, dry-runs it on a branch, then ships the migration and code changes.',
    inputLabel: 'Repo + schema change', outputLabel: 'Migration + code PR',
    placeholder: 'Describe the schema change',
    tools: ['db', 'shell', 'git', 'fs'],
    approvals: ['Any DDL on a shared database', 'DROP / TRUNCATE', 'DELETE without WHERE'],
    criteria: ['Dry run succeeds on a database branch', 'Rollback SQL is included', 'App code updated for the new schema'],
    checks: ['Dry run', 'Tests', 'Rollback verified'],
  },
  {
    id: 'dep_upgrade', name: 'Dependency upgrade', shortLabel: 'Upgrade dependencies', icon: 'download',
    description: 'Upgrades a package, fixes breaking changes and verifies the build.',
    inputLabel: 'Repo + package', outputLabel: 'PR with upgrade and fixes',
    placeholder: 'Which package should be upgraded, and to which version?',
    tools: ['shell', 'fs', 'git', 'tests'],
    approvals: ['Post-install scripts from untrusted packages'],
    criteria: ['Build and tests pass', 'Changelog breaking changes addressed'],
    checks: ['Tests', 'Build', 'Lockfile diff reviewed'],
  },
  {
    id: 'test_backfill', name: 'Test backfill', shortLabel: 'Add tests', icon: 'flask',
    description: 'Writes tests for untested code until a coverage target is met.',
    inputLabel: 'Repo + coverage target', outputLabel: 'PR adding tests',
    placeholder: 'Which module needs tests, and what coverage do you want?',
    tools: ['fs', 'shell', 'tests', 'git'],
    approvals: [],
    criteria: ['Coverage target reached', 'No flaky tests'],
    checks: ['Tests (3 runs)', 'Coverage report'],
  },
  {
    id: 'deploy_preview', name: 'Deploy preview', shortLabel: 'Deploy a preview', icon: 'rocket',
    description: 'Builds a branch and returns a live preview URL with a database branch.',
    inputLabel: 'Repo + branch', outputLabel: 'Preview URL',
    placeholder: 'Which repo and branch should get a preview?',
    tools: ['deploy', 'shell', 'browser'],
    approvals: ['Production deploys'],
    criteria: ['Preview loads without errors'],
    checks: ['Build', 'Smoke test in browser'],
  },
  {
    id: 'zip_import', name: 'ZIP import', shortLabel: 'Import a ZIP', icon: 'zip',
    description: 'Unpacks a ZIP into a repo, fixes the setup and opens a PR.',
    inputLabel: 'ZIP + repo', outputLabel: 'PR with imported code',
    placeholder: 'Upload a ZIP and say where it should go',
    tools: ['fs', 'shell', 'git'],
    approvals: ['Running untrusted code'],
    criteria: ['Project installs and builds', 'No secrets committed'],
    checks: ['Build', 'Secret scan'],
  },
  {
    id: 'issue_triage', name: 'Issue triage', shortLabel: 'Triage issues', icon: 'list',
    description: 'Labels and comments on open issues and links related PRs.',
    inputLabel: 'Repo', outputLabel: 'Labels, comments and linked PRs',
    placeholder: 'Which repo should be triaged?',
    tools: ['GitHub API'],
    approvals: ['Bulk comments over 20 issues'],
    criteria: ['Every open issue has a label'],
    checks: ['No duplicate comments'],
  },
];

export const jobById = (id?: string | null) => JOB_TEMPLATES.find((j) => j.id === id);
